# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        name: Build React Project
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run-script build
          - mkdir packaged
          - tar -czvf packaged/package-${BITBUCKET_BUILD_NUMBER}.tar.gz -C build .
        artifacts:
          - packaged/**
    - step:
        name: Deploy to Web
        image: alpine
        #trigger: manual
        deployment: staging
        script:
          - mkdir upload
          - tar -xf packaged/package-${BITBUCKET_BUILD_NUMBER}.tar.gz -C upload
          - apk update && apk add openssh rsync
          - rsync -a  -e "ssh -o StrictHostKeyChecking=no" --delete upload/ $USERNAME@$SERVER:data/react-${BITBUCKET_BUILD_NUMBER}
          - ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER "rm -r httpdocs/providers/*"
          - ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER "rsync -vau --remove-source-files 'data/react-${BITBUCKET_BUILD_NUMBER}/' 'httpdocs/providers'"
          - ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER "chmod -R u+rwX,go+rX,go-w httpdocs/providers"
          - ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER "rm -rf data/react-${BITBUCKET_BUILD_NUMBER}"